# Generated by Django 4.2.20 on 2025-11-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detalleventa",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="cantidad",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="precio_unitario",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
