# Generated by Django 4.2.20 on 2025-11-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ventas", "0001_initial"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientostock",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ventas.venta",
            ),
        ),
        migrations.AddField(
            model_name="entradamenu",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entradas",
                to="inventario.menulateral",
            ),
        ),
        migrations.AddField(
            model_name="entradamenu",
            name="padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subentradas",
                to="inventario.entradamenu",
            ),
        ),
        migrations.AddField(
            model_name="categoria",
            name="padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hijos",
                to="inventario.categoria",
            ),
        ),
        migrations.AddField(
            model_name="atributo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                help_text="Si es NULL, atributo global",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.categoria",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together={("producto", "almacen")},
        ),
        migrations.AlterUniqueTogether(
            name="productoatributo",
            unique_together={("producto", "atributo")},
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["categoria", "activo"], name="inventario__categor_c6db1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["codigo_barras"], name="inventario__codigo__f8dec9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["slug"], name="inventario__slug_1cbdbd_idx"),
        ),
    ]
