# Generated by Django 4.2.20 on 2025-11-29 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="inventario__categor_c6db1b_idx",
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="inventario__codigo__f8dec9_idx",
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="inventario__slug_1cbdbd_idx",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="codigo_barras",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="pais",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="inventario.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="margen",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="producto",
            name="productor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="inventario.productor",
            ),
        ),
    ]
